# Generated by Django 3.2.25 on 2024-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_image_updated_at_tweet_updated_at_video_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
