# Generated by Django 5.1.4 on 2025-01-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_user_login_alter_person_username'),
        ('profile', '0004_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='mentions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='trends',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='profile.tweet')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
    ]
