FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copy the Django application code
COPY myapp/ ./myapp/
COPY manage.py ./
COPY Cloud_Hoskie/ ./Cloud_Hoskie/

# Expose the port that Gunicorn will run on
EXPOSE 8000

CMD ["gunicorn", "Cloud_Hoskie.wsgi:application", "--bind", "0.0.0.0:8000"]
