# Generated by Django 5.1.1 on 2024-10-12 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('relationship_status', models.CharField(choices=[('single', 'Single'), ('in_relationship', 'In a Relationship'), ('engaged', 'Engaged'), ('married', 'Married'), ('complicated', "It's Complicated")], max_length=15)),
                ('sexual_orientation', models.CharField(choices=[('gay', 'Gay'), ('lesbian', 'Lesbian'), ('straight', 'Straight'), ('other', 'Other')], max_length=10)),
                ('race', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('asian', 'Asian'), ('hispanic', 'Hispanic'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('social_media_api', models.URLField()),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
