# Generated by Django 5.1.1 on 2024-11-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('verified', models.BooleanField(default=False)),
                ('login_count', models.IntegerField(default=0)),
                ('session_active', models.BooleanField(default=False)),
            ],
        ),
    ]
