# Generated by Django 5.1.1 on 2024-11-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_logoutactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
